server:
  port: 8888



#spring:
#  data:
#    mongodb:
#      host: 192.168.129.3
#      port: 27017
#      database: demoDB
spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://172.28.85.25:3306/zbase?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8&useOldAliasMetadataBehavior=true
      username: zbase
      password: dw123456
  jpa:
      database: mysql
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true